version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: badminton_postgres
    environment:
      POSTGRES_USER: user=postgres
      POSTGRES_PASSWORD: dbname=badminton_db
      POSTGRES_DB: password=yourpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: